### ISSUE TITLE
availablePanelsForDetail($request) bug

### ISSUE THREAD

**Issue by wouter-ham** [dcasia/conditional-container#47]
`Declaration of DigitalCreative\ConditionalContainer\HasConditionalContainer::availablePanelsForDetail($request) should be compatible with Laravel\Nova\Resource::availablePanelsForDetail(Laravel\Nova\Http\Requests\NovaRequest $request, Laravel\Nova\Resource $resource)`

@mennotempelaar

**Comment by mennotempelaar** [comment]
This was a bug in our code for websites. There was a version constraint in one of our packages which would'nt update the conditional-container package.

**This issue is solved**

**Comment by shad0matic** [comment]
Hi, I still have the same problem today  right after installing package with composer,
is it because I don't have the correct version ?

**Comment by milewski** [comment]
@shad0matic I believe you need to have the latest version of nova for this to work, if your version of nova is old you will get an "old version" of this package due to a constrain set on the composer.json

**Comment by shad0matic** [comment]
And you are right, I was running 3.10.0,
problem fixed by upgrading to 3.15.0

Thanks for your help
